server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

logging:
  level: INFO
  appenders:
  - type: console

healthCheck: OK

assets:
  mappings:
    /swagger-ui: /swagger-ui

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:payments
#  url: jdbc:h2:~/payments
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    hibernate.hbm2ddl.import_files: /import/accounts.sql
